### PR TITLE
Add queue

### PR DESCRIPTION
**Pull request by e1leet**

### CODE REVIEW

**Comment by tomakado** [comment]
Hi @e1leet!

Thank you for contribution. Could you please also add some unit tests for `Queue` using `stretchr/testify`? I will add tests for hash set a bit later too.

**Comment by e1leet** [comment]
@tomakado ok, I'll probably add tests tomorrow.

**Comment by e1leet** [comment]
@tomakado I am very bad at writing tests. Take a close look to see if everything is ok. Text me later, I'll fix it

**Comment by tomakado** [comment]
@e1leet thanks! I'll check today later or tomorrow

**Comment by tomakado** [comment]
LGTM

**Pull request merged**
